server:
  port: 8081

#spring:
#  freemarker:
#    suffix: .html
#    template-loader-path: /templates/
#    allow-request-override: false
#
mybatis:
  mapper-locations: classpath:mapper/*.xml   #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xie.pojo      # 注意：对应实体类的路径
